#! /bin/sh

# Autostart programs and swapping esc with caps
sxhkd &
~/.fehbg &
#. ~/.config/polybar/launch.sh

bspc monitor -d web msc msc edt cht wrk vrt prv cfg trm

bspc config border_width                5
bspc config window_gap                  30
bspc config top_padding                 0
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config normal_border_color		      "#2E3440"
bspc config active_border_color	              "#1e1e1e"
bspc config focused_border_color	      "#8FBCBB"
bspc config presel_feedback_color	      "#3b4252"
bspc config urgent_border_color 	      "#dd2727"

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a Discord desktop='^5'
bspc rule -a 'Virtual Machine Manager' desktop='^7'
bspc rule -a 'emacs' desktop='^4'
