#! /bin/sh

# Autostart programs and swapping esc with caps
compton &
sxhkd &
xinput --set-prop 13 'libinput Accel Speed' -1 &
setxkbmap -option "caps:swapescape" &
$HOME/.config/dunst/wrapper.sh &
~/.fehbg &
dbus-launch fcitx &
. ~/.config/polybar/launch.sh

bspc monitor -d trm edt web ntf cht wrk vrt prv cfg

bspc config border_width                1
bspc config window_gap                  10
bspc config top_padding                 30
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	              "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc config focus_follows_pointer true

xdotool below -t $(xdo id -n root) $(xdo id -a polybar)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^3'
bspc rule -a Station desktop='^2'
bspc rule -a Atom desktop='^2'
bspc rule -a Oni desktop='^2'
bspc rule -a 'Virtual Machine Manager' desktop='^7'
