# format = """
# [┌───](bold green) $directory$rust$package
# [└─](bold green) """

[character]
format = "[\\$](bold green) "
error_symbol = "✗"
success_symbol = "[\\$](bold green) "
use_symbol_for_status = true
