#! /bin/sh

# Autostart programs and swapping esc with caps
sxhkd &
~/.fehbg &
. ~/.config/polybar/launch.sh
. ~/.bin/libinput-init.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width                3
bspc config window_gap                  20
bspc config top_padding                 55
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config focus_follows_pointer true

# colors from Xresources
bspc config normal_border_color	              $(xrdb -query | grep "*.foreground-alt" | cut -f 2)
bspc config active_border_color	              $(xrdb -query | grep "*.foreground-alt" | cut -f 2)
bspc config focused_border_color	      $(xrdb -query | grep "*.highlight" | cut -f 2)
bspc config presel_feedback_color	      $(xrdb -query | grep "*.foreground-alt" | cut -f 2)
bspc config urgent_border_color 	      $(xrdb -query | grep "*.alert" | cut -f 2)


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a VSCodium desktop='^3'
bspc rule -a zsh desktop='^2'
bspc rule -a Discord desktop='^4'
bspc rule -a 'Virtual Machine Manager' desktop='^7'
bspc rule -a mpv state=fullscreen
bspc rule -a editor state=fullscreen desktop='^3'
bspc rule -a zathura state=tiling
