#! /bin/sh

source $HOME/.config/bspwm/autostart.sh
source $HOME/.config/bspwm/rules
source $HOME/.config/bspwm/colors

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width                3
bspc config window_gap                  20
bspc config top_padding                 55
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config focus_follows_pointer true
