export EDITOR=/usr/bin/nvim
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export PATH="$PATH:/home/faith/.local/bin"
export PATH="/home/faith/.npm/bin:/home/faith/.bin:/home/faith/.carton/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export BROWSER=/usr/bin/chromium-browser-privacy
