#!/bin/sh

# Autostart programs and swapping esc with caps
killall sxhkd
sxhkd &
killall dunst
dunst &
~/.fehbg &
picom -b
~/.config/polybar/launch.sh &

# Colors
bspc config active_border_color "#1E1E2E"
bspc config focused_border_color "#b4befe"
bspc config normal_border_color "#1E1E2E"
bspc config presel_feedback_color "#73daca"

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width 2
bspc config window_gap 20
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true

# terminals
bspc rule -a Alacritty:Alacritty desktop='^10' follow=on
bspc rule -a floating_terminal state=floating

# browsers
bspc rule -a Firefox desktop='^1'
bspc rule -a Chromium desktop='^1'

# chatting & socials
bspc rule -a discord desktop='^3'
bspc rule -a whatsapp desktop='^3'
bspc rule -a tweetdeck desktop='^3'

# editors
bspc rule -a *:editor state=fullscreen desktop='^4' follow=on
bspc rule -a VSCodium desktop='^4'

# email
bspc rule -a gmail desktop='^6'

# misc
bspc rule -a Virt-manager desktop='^7' state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiling
bspc rule -a feh state=floating
bspc rule -a mpv state=fullscreen
bspc rule -a notion desktop='^5'
bspc rule -a *:file_manager state=floating
bspc rule -a xfreerdp3 state=floating center=true rectangle=2560x1440+0+0
bspc rule -a polybar state=floating center=true
